import { nanumsqneo } from '@/assets/fonts';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${nanumsqneo.variable}`}>
      <body className="max-w-screen flex flex-col bg-zinc-700">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
